default:
  SECRET_KEY: "osx!*ihr0uk83!^$hh!bdo(m^w1vkc2y0o%3*nmo%6j*9b5l!3"
  DEBUG: true
  ALLOWED_HOSTS: []

heroku:
  DEBUG: false
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - schedulebntu.herokuapp.com
